package cn.edu.henu.rjxy.lms.model;
// Generated 2015-10-23 19:30:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;

/**
 * Teacher generated by hbm2java
 */
@Entity(name = "Teacher")
public class Teacher implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "teacher_Id")
     private Integer teacherId;
    @Column(name = "teacher_Sn", length= 45, nullable = false)
     private String teacherSn;//工号
    @Column(name = "teacher_Name", length= 45, nullable = false)
     private String teacherName;//姓名
    @Column(name = "teacher_Idcard", length= 18, nullable = false)
     private String teacherIdcard;//身份证 
    @Column(name = "teacher_College", length= 18, nullable = false)
     private String teacherCollege;//yuan
    @Column(name = "teacher_Img", length= 18, nullable = true, columnDefinition = "int(10)  default 0")
     private int teacherImg;
    @Column(name = "teacher_Tel", length= 20, nullable = false)
     private String teacherTel;//手机号 
    @Column(name = "teacher_Qq", length= 20, nullable = false)
     private String teacherQq;//qq 
    @Column(name = "teacher_Pwd", length= 45, nullable = false)
     private String teacherPwd;//密码 

     private boolean teacherSex;//性别 
    @Column(name = "teacher_Position", length= 45, nullable = false)
     private String teacherPosition;//职称 
    @Column(name = "teacher_Enrolling", nullable = false)
     private Date teacherEnrolling;//注册时间
    @Column(name = "teacher_role_value", length= 45, nullable = false)
     private int teacherRoleValue;
    @OneToMany(cascade = CascadeType.ALL,fetch = FetchType.EAGER)
    @JoinColumn(name = "teacher_Id")
     private Set<TermCourse> termCourse;
     

    public Teacher() {
    }

    public Teacher(String teacherSn, String teacherName, String teacherIdcard, String teacherCollege, String teacherTel, String teacherQq, String teacherPwd, boolean teacherSex, String teacherPosition, Date teacherEnrolling, int teacherRoleValue) {
       this.teacherSn = teacherSn;
       this.teacherName = teacherName;
       this.teacherIdcard = teacherIdcard;
       this.teacherCollege = teacherCollege;
       this.teacherTel = teacherTel;
       this.teacherQq = teacherQq;
       this.teacherPwd = teacherPwd;
       this.teacherSex = teacherSex;
       this.teacherPosition = teacherPosition;
       this.teacherEnrolling = teacherEnrolling;
       this.teacherRoleValue = teacherRoleValue;
    }
    
    public void copy(TempTeacher tempTeacher){
            this.setTeacherId(tempTeacher.getTeacherId());
            this.setTeacherSn(tempTeacher.getTeacherSn());
            this.setTeacherName(tempTeacher.getTeacherName());
            this.setTeacherIdcard(tempTeacher.getTeacherIdcard());
            this.setTeacherCollege(tempTeacher.getTeacherCollege());
            this.setTeacherTel(tempTeacher.getTeacherTel());
            this.setTeacherQq(tempTeacher.getTeacherQq());
            this.setTeacherPwd(tempTeacher.getTeacherPwd());
            this.setTeacherSex(tempTeacher.getTeacherSex());
            this.setTeacherPosition(tempTeacher.getTeacherPosition());
            this.setTeacherEnrolling(tempTeacher.getTeacherEnrolling());
            String str2[] = {"教务员", "院长", "教工", "系统管理员"};
            int str3[] = {5, 7, 4, 15};
            for (int j = 0; j < 4; j++) {
             if(str2[j].equals(tempTeacher.getTeacherPosition())){this.setTeacherRoleValue(str3[j]);}
            }
                              
    }
   
    public int getTeacherRoleValue() {
        return this.teacherRoleValue;
    }
    
    public void setTeacherRoleValue(int teacherRoleValue) {
        this.teacherRoleValue = teacherRoleValue;
    }

    /**
     * @return the teacherId
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * @param teacherId the teacherId to set
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * @return the teacherSn
     */
    public String getTeacherSn() {
        return teacherSn;
    }

    /**
     * @param teacherSn the teacherSn to set
     */
    public void setTeacherSn(String teacherSn) {
        this.teacherSn = teacherSn;
    }

    /**
     * @return the teacherName
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * @param teacherName the teacherName to set
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    /**
     * @return the teacherIdcard
     */
    public String getTeacherIdcard() {
        return teacherIdcard;
    }

    /**
     * @param teacherIdcard the teacherIdcard to set
     */
    public void setTeacherIdcard(String teacherIdcard) {
        this.teacherIdcard = teacherIdcard;
    }

    /**
     * @return the teacherCollegeId
     */
    public String getTeacherCollege() {
        return teacherCollege;
    }


    public void setTeacherCollege(String teacherCollege) {
        this.teacherCollege = teacherCollege;
    }

    /**
     * @return the teacherTel
     */
    public String getTeacherTel() {
        return teacherTel;
    }

    /**
     * @param teacherTel the teacherTel to set
     */
    public void setTeacherTel(String teacherTel) {
        this.teacherTel = teacherTel;
    }

    /**
     * @return the teacherQq
     */
    public String getTeacherQq() {
        return teacherQq;
    }

    /**
     * @param teacherQq the teacherQq to set
     */
    public void setTeacherQq(String teacherQq) {
        this.teacherQq = teacherQq;
    }

    /**
     * @return the teacherPwd
     */
    public String getTeacherPwd() {
        return teacherPwd;
    }

    /**
     * @param teacherPwd the teacherPwd to set
     */
    public void setTeacherPwd(String teacherPwd) {
        this.teacherPwd = teacherPwd;
    }

    /**
     * @return the teacherSex
     */
    public boolean getTeacherSex() {
        return isTeacherSex();
    }

    /**
     * @param teacherSex the teacherSex to set
     */
    public void setTeacherSex(boolean teacherSex) {
        this.teacherSex = teacherSex;
    }

    /**
     * @return the teacherPositionId
     */
    public String getTeacherPosition() {
        return teacherPosition;
    }


    public void setTeacherPosition(String teacherPosition) {
        this.teacherPosition = teacherPosition;
    }

    /**
     * @return the teacherEnrolling
     */
    public Date getTeacherEnrolling() {
        return teacherEnrolling;
    }

    /**
     * @param teacherEnrolling the teacherEnrolling to set
     */
    public void setTeacherEnrolling(Date teacherEnrolling) {
        this.teacherEnrolling = teacherEnrolling;
    }


    /**
     * @return the termCourse
     */
    public Set<TermCourse> getTermCourse() {
        return termCourse;
    }

    /**
     * @param termCourse the termCourse to set
     */
    public void setTermCourse(Set<TermCourse> termCourse) {
        this.termCourse = termCourse;
    }

    /**
     * @return the teacherImg
     */
    public int getTeacherImg() {
        return teacherImg;
    }

    /**
     * @param teacherImg the teacherImg to set
     */
    public void setTeacherImg(int teacherImg) {
        this.teacherImg = teacherImg;
    }

    /**
     * @return the teacherSex
     */
    public boolean isTeacherSex() {
        return teacherSex;
    }




}


