package cn.edu.henu.rjxy.lms.model;
// Generated 2015-10-23 19:30:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TempStudent generated by hbm2java
 */
public class TempStudentWithoutPwd  implements java.io.Serializable {



     private String studentSn;//学号
     private String studentName;//姓名
     private String studentIdcard;// 身份证 
     private boolean studentSex;//性别
     private int studentGrade; // 年级
     private String studentCollege;//院系
     private String studentTel;//手机号
     private String studentQq;//qq

    public TempStudentWithoutPwd() {
    }

    public TempStudentWithoutPwd(String studentSn, String studentName, String studentIdcard, int studentGrade, String
            studentCollege, String studentTel, String studentQq, String studentPwd, boolean studentSex, Date studentEnrolling) {
       this.studentSn = studentSn;
       this.studentName = studentName;
       this.studentIdcard = studentIdcard;
       this.studentGrade = studentGrade;
       this.studentCollege = studentCollege;
       this.studentTel = studentTel;
       this.studentQq = studentQq;
       this.studentSex = studentSex;

    }
    public void copy(TempStudent tempStudent) {
       this.studentSn = tempStudent.getStudentSn();
       this.studentName = tempStudent.getStudentName();
       this.studentIdcard = tempStudent.getStudentIdcard();
       this.studentGrade = tempStudent.getStudentGrade();
       this.studentCollege = tempStudent.getStudentCollege();
       this.studentTel = tempStudent.getStudentTel();
       this.studentQq = tempStudent.getStudentQq();
       this.studentSex = tempStudent.getStudentSex();
    }
   

    public String getStudentSn() {
        return this.studentSn;
    }
    
    public void setStudentSn(String studentSn) {
        this.studentSn = studentSn;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public String getStudentIdcard() {
        return this.studentIdcard;
    }
    
    public void setStudentIdcard(String studentIdcard) {
        this.studentIdcard = studentIdcard;
    }
    public int getStudentGrade() {
        return this.studentGrade;
    }
    
    public void setStudentGrade(int studentGrade) {
        this.studentGrade = studentGrade;
    }
    public String getStudentCollege() {
        return this.studentCollege;
    }
    
    public void setStudentCollege(String studentCollege) {
        this.studentCollege = studentCollege;
    }
    public String getStudentTel() {
        return this.studentTel;
    }
    
    public void setStudentTel(String studentTel) {
        this.studentTel = studentTel;
    }
    public String getStudentQq() {
        return this.studentQq;
    }
    
    public void setStudentQq(String studentQq) {
        this.studentQq = studentQq;
    }

    public boolean isStudentSex() {
        return this.studentSex;
    }
    
    public void setStudentSex(boolean studentSex) {
        this.studentSex = studentSex;
    }

}


