package cn.edu.henu.rjxy.lms.model;
// Generated 2015-10-23 19:30:46 by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class TermCourseInfo  implements java.io.Serializable {


    private Integer id;
    private Integer term;
    private Course course;
    private String courseBInfo;
    private String courseOutline;

    

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the term
     */
    public Integer getTerm() {
        return term;
    }

    /**
     * @param term the term to set
     */
    public void setTerm(Integer term) {
        this.term = term;
    }

    /**
     * @return the course
     */
    public Course getCourse() {
        return course;
    }

    /**
     * @param course the course to set
     */
    public void setCourse(Course course) {
        this.course = course;
    }

    /**
     * @return the courseBInfo
     */
    public String getCourseBInfo() {
        return courseBInfo;
    }

    /**
     * @param courseBInfo the courseBInfo to set
     */
    public void setCourseBInfo(String courseBInfo) {
        this.courseBInfo = courseBInfo;
    }

    /**
     * @return the courseOutline
     */
    public String getCourseOutline() {
        return courseOutline;
    }

    /**
     * @param courseOutline the courseOutline to set
     */
    public void setCourseOutline(String courseOutline) {
        this.courseOutline = courseOutline;
    }


}


