package cn.edu.henu.rjxy.lms.model;
// Generated 2015-10-11 15:39:10 by Hibernate Tools 4.3.1



/**
 * College generated by hbm2java
 */
public class College  implements java.io.Serializable {


     private Integer collegeId;
     private String collegeName;//院的名字
     private int collegeSn;//院号

    public College() {
    }

    public College(String collegeName, int collegeSn) {
       this.collegeName = collegeName;
       this.collegeSn = collegeSn;
    }
   
    public Integer getCollegeId() {
        return this.collegeId;
    }
    
    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }
    public String getCollegeName() {
        return this.collegeName;
    }
    
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }
    public int getCollegeSn() {
        return this.collegeSn;
    }
    
    public void setCollegeSn(int collegeSn) {
        this.collegeSn = collegeSn;
    }




}


