package cn.edu.henu.rjxy.lms.model;
// Generated 2015-10-11 15:39:10 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TempStudent generated by hbm2java
 */
public class TempStudent  implements java.io.Serializable {


     private Integer stuId;
     private int stuSn;//学号
     private String stuName;//姓名
     private String stuIdcard;//身份证
     private boolean stuSex;//性别
     private Date stuBirthday;//不要
     private String stuTel;//电话
     private String stuQq;//qq
     private String stuEmail;//不要
     private String stuPwd;//密码
     private String stuGrade;//年级
     private int stuCollegeId;//院
     private Integer stuDepartId;//不要
     private Integer stuClassId;//不要班号
     private Date stuEnrolling;//注册时间

    public TempStudent() {
    }

	
    public TempStudent(int stuSn, String stuName, String stuIdcard, boolean stuSex, String stuPwd, String stuGrade, int stuCollegeId, Date stuEnrolling) {
        this.stuSn = stuSn;
        this.stuName = stuName;
        this.stuIdcard = stuIdcard;
        this.stuSex = stuSex;
        this.stuPwd = stuPwd;
        this.stuGrade = stuGrade;
        this.stuCollegeId = stuCollegeId;
        this.stuEnrolling = stuEnrolling;
    }
    public TempStudent(int stuSn, String stuName, String stuIdcard, boolean stuSex, Date stuBirthday, String stuTel, String stuQq, String stuEmail, String stuPwd, String stuGrade, int stuCollegeId, Integer stuDepartId, Integer stuClassId, Date stuEnrolling) {
       this.stuSn = stuSn;
       this.stuName = stuName;
       this.stuIdcard = stuIdcard;
       this.stuSex = stuSex;
       this.stuBirthday = stuBirthday;
       this.stuTel = stuTel;
       this.stuQq = stuQq;
       this.stuEmail = stuEmail;
       this.stuPwd = stuPwd;
       this.stuGrade = stuGrade;
       this.stuCollegeId = stuCollegeId;
       this.stuDepartId = stuDepartId;
       this.stuClassId = stuClassId;
       this.stuEnrolling = stuEnrolling;
    }
   
    public Integer getStuId() {
        return this.stuId;
    }
    
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }
    public int getStuSn() {
        return this.stuSn;
    }
    
    public void setStuSn(int stuSn) {
        this.stuSn = stuSn;
    }
    public String getStuName() {
        return this.stuName;
    }
    
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }
    public String getStuIdcard() {
        return this.stuIdcard;
    }
    
    public void setStuIdcard(String stuIdcard) {
        this.stuIdcard = stuIdcard;
    }
    public boolean isStuSex() {
        return this.stuSex;
    }
    
    public void setStuSex(boolean stuSex) {
        this.stuSex = stuSex;
    }
    public Date getStuBirthday() {
        return this.stuBirthday;
    }
    
    public void setStuBirthday(Date stuBirthday) {
        this.stuBirthday = stuBirthday;
    }
    public String getStuTel() {
        return this.stuTel;
    }
    
    public void setStuTel(String stuTel) {
        this.stuTel = stuTel;
    }
    public String getStuQq() {
        return this.stuQq;
    }
    
    public void setStuQq(String stuQq) {
        this.stuQq = stuQq;
    }
    public String getStuEmail() {
        return this.stuEmail;
    }
    
    public void setStuEmail(String stuEmail) {
        this.stuEmail = stuEmail;
    }
    public String getStuPwd() {
        return this.stuPwd;
    }
    
    public void setStuPwd(String stuPwd) {
        this.stuPwd = stuPwd;
    }
    public String getStuGrade() {
        return this.stuGrade;
    }
    
    public void setStuGrade(String stuGrade) {
        this.stuGrade = stuGrade;
    }
    public int getStuCollegeId() {
        return this.stuCollegeId;
    }
    
    public void setStuCollegeId(int stuCollegeId) {
        this.stuCollegeId = stuCollegeId;
    }
    public Integer getStuDepartId() {
        return this.stuDepartId;
    }
    
    public void setStuDepartId(Integer stuDepartId) {
        this.stuDepartId = stuDepartId;
    }
    public Integer getStuClassId() {
        return this.stuClassId;
    }
    
    public void setStuClassId(Integer stuClassId) {
        this.stuClassId = stuClassId;
    }
    public Date getStuEnrolling() {
        return this.stuEnrolling;
    }
    
    public void setStuEnrolling(Date stuEnrolling) {
        this.stuEnrolling = stuEnrolling;
    }




}


