package cn.edu.henu.rjxy.lms.bean;
// Generated 2014-8-12 13:22:52 by Hibernate Tools 3.6.0
//本类用于描述班级
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classes generated by hbm2java
 * 对应lms中classes表
 */
@Entity
@Table(name = "classes", catalog = "lms"
)
public class Classes implements java.io.Serializable {
    //班级id
    private Integer classId;
    //班级的上级系
    private Depart depart;
    //班级的上级院
    private College college;
    //班级的上级年级
    private Grade grade;
    //班级名称
    private String className;
    //班级中的学生
    private Set<Student> student;
    //班级中的临时表中的学生
    private Set<TempStudent> tempStudents;

    public Classes() {
    }

    public Classes(String className) {
        this.className = className;
    }

    public Classes(Depart depart, College college, String className) {
        this.depart = depart;
        this.college = college;
        this.className = className;
    }

    //标记bean属性和表中关键字的对应关系
    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "class_id", unique = true, nullable = false)
    public Integer getClassId() {
        return this.classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }
    //多对一映射关系，班级的上级系id
    @ManyToOne(optional = false)
    @JoinColumn(name = "class_upper_depart_id", nullable = false)
    public Depart getDepart() {
        return this.depart;
    }

    public void setDepart(Depart depart) {
        this.depart = depart;
    }

    @ManyToOne(optional = false)
    @JoinColumn(name = "class_upper_college_id", nullable = false)

    public College getCollege() {
        return this.college;
    }

    public void setCollege(College college) {
        this.college = college;
    }
    //班级名称，长度为20
    @Column(name = "class_name", length = 20)
    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * @return the grade
     * 多对一映射，对应班级的上级年级
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "class_grade_id", nullable = false)
    public Grade getGrade() {
        return grade;
    }

    /**
     * @param grade the grade to set
     */
    public void setGrade(Grade grade) {
        this.grade = grade;
    }

    /**
     * @return the student
     * 一对多，级联更新和级联删除
     */
    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE},
            mappedBy = "classes")
    public Set<Student> getStudent() {
        return student;
    }

    /**
     * @param student the student to set
     */
    public void setStudent(Set<Student> student) {
        this.student = student;
    }

    /**
     * @return the tempStudents
     */
    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE},
            mappedBy = "classes")
    public Set<TempStudent> getTempStudents() {
        return tempStudents;
    }

    /**
     * @param tempStudents the tempStudents to set
     */
    public void setTempStudents(Set<TempStudent> tempStudents) {
        this.tempStudents = tempStudents;
    }
}
