package cn.edu.henu.rjxy.lms.bean;
// Generated 2014-8-12 13:22:52 by Hibernate Tools 3.6.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Depart generated by hbm2java
 */
@Entity
@Table(name = "depart", catalog = "lms")
public class Depart implements Serializable {

    private int departId;

    private String departName;
    private College college;

    private Set<Classes> classes;
    private Set<Student> students;
    private Set<Teacher> teachers;
    private Set<TempStudent> tempStudents;
    private Set<TempTeacher> tempTeachers;

    public Depart() {
    }

    public Depart(int departId) {
        this.departId = departId;
    }

    public Depart(String departName) {
        //this.classes = new HashSet<>(0);
        this.departName = departName;
    }

    public Depart(int departId, College college, String departName) {
        this.departId = departId;
        //this.college = college;
        this.departName = departName;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "depart_id", unique = true, nullable = false)
    public int getDepartId() {
        return this.departId;
    }

    public void setDepartId(int departId) {
        this.departId = departId;
    }

    @ManyToOne(optional = false)
    @JoinColumn(name = "uppercollege_id")
    public College getCollege() {
        return this.college;
    }

    public void setCollege(College college) {
        this.college = college;
    }

    /**
     *
     * @return
     */
    @Column(name = "depart_name", length = 20)
    public String getDepartName() {
        return this.departName;
    }

    public void setDepartName(String departName) {
        this.departName = departName;
    }

    /**
     * @return the classes
     */
    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE},
            mappedBy = "depart")
    public Set<Classes> getClasses() {
        return classes;
    }

    /**
     * @param classes the classes to set
     */
    public void setClasses(Set<Classes> classes) {
        this.classes = classes;
    }

    public void addClasses(Classes classes) {
        classes.setDepart(this);//因为classes为n端，负责维护关系这句必须有
        //System.out.print(depart.getDepartName());
        if (this.classes == null) {
            System.out.print("depart_classes_null");
            this.classes = new HashSet<Classes>(0);
        }
        this.classes.add(classes);
    }

    /**
     * @return the students
     */
    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE},
            mappedBy = "depart")
    public Set<Student> getStudents() {
        return students;
    }

    /**
     * @param students the students to set
     */
    public void setStudents(Set<Student> students) {
        this.students = students;
    }

    /**
     * @return the teachers
     */
    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE},
            mappedBy = "depart")
    public Set<Teacher> getTeachers() {
        return teachers;
    }

    /**
     * @param teachers the teachers to set
     */
    public void setTeachers(Set<Teacher> teachers) {
        this.teachers = teachers;
    }

    /**
     * @return the tempStudents
     */
    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE},
            mappedBy = "depart")
    public Set<TempStudent> getTempStudents() {
        return tempStudents;
    }

    /**
     * @param tempStudents the tempStudents to set
     */
    public void setTempStudents(Set<TempStudent> tempStudents) {
        this.tempStudents = tempStudents;
    }

    /**
     * @return the tempTeachers
     */
    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE},
            mappedBy = "depart")
    public Set<TempTeacher> getTempTeachers() {
        return tempTeachers;
    }

    /**
     * @param tempTeachers the tempTeachers to set
     */
    public void setTempTeachers(Set<TempTeacher> tempTeachers) {
        this.tempTeachers = tempTeachers;
    }

}
