package cn.edu.henu.rjxy.lms.bean;
// Generated 2014-8-12 13:22:52 by Hibernate Tools 3.6.0

import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "grade", catalog = "lms")
public class Grade implements java.io.Serializable {

    private Integer id;
    private String grade;
    private Set<Classes> classes;
    private Set<Student> student;

    public Grade() {
    }

    public Grade(String grade) {
        this.grade = grade;
    }

    /**
     * @return the id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "grade", unique = true, nullable = false, length = 6)
    public String getGrade() {
        return this.grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * @return the classes
     */
    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE},
            mappedBy = "grade")
    public Set<Classes> getClasses() {
        return classes;
    }

    /**
     * @param classes the classes to set
     */
    public void setClasses(Set<Classes> classes) {
        this.classes = classes;
    }

    /**
     * @return the student
     */
    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE},
            mappedBy = "grade")
    public Set<Student> getStudent() {
        return student;
    }

    /**
     * @param student the student to set
     */
    public void setStudent(Set<Student> student) {
        this.student = student;
    }
}
