package cn.edu.henu.rjxy.lms.bean;
// Generated 2014-8-12 13:22:52 by Hibernate Tools 3.6.0

import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "position", catalog = "lms"
)
public class Position implements java.io.Serializable {

    private Integer Id;
    private String position;
    private Set<Teacher> teachers;
    private Set<TempTeacher> tempTeachers;

    public Position() {
    }

    public Position(String position) {
        this.position = position;
    }

    /**
     * @return the Id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Integer getId() {
        return Id;
    }

    /**
     * @param Id the Id to set
     */
    public void setId(Integer Id) {
        this.Id = Id;
    }

    @Column(name = "position", unique = true, nullable = false, length = 20)
    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * @return the teachers
     */
    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE},
            mappedBy = "position")
    public Set<Teacher> getTeachers() {
        return teachers;
    }

    /**
     * @param teachers the teachers to set
     */
    public void setTeachers(Set<Teacher> teachers) {
        this.teachers = teachers;
    }

    /**
     * @return the tempTeachers
     */
    @OneToMany(cascade = {CascadeType.MERGE, CascadeType.REMOVE},
            mappedBy = "position")
    public Set<TempTeacher> getTempTeachers() {
        return tempTeachers;
    }

    /**
     * @param tempTeachers the tempTeachers to set
     */
    public void setTempTeachers(Set<TempTeacher> tempTeachers) {
        this.tempTeachers = tempTeachers;
    }

}
