package cn.edu.henu.rjxy.lms.model;
// Generated 2015-10-23 19:30:46 by Hibernate Tools 4.3.1



/**
 * Depart generated by hbm2java
 */
public class Depart  implements java.io.Serializable {


     private Integer departId;
     private String departName;
     private int departSn;

    public Depart() {
    }

    public Depart(String departName, int departSn) {
       this.departName = departName;
       this.departSn = departSn;
    }
   
    public Integer getDepartId() {
        return this.departId;
    }
    
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }
    public String getDepartName() {
        return this.departName;
    }
    
    public void setDepartName(String departName) {
        this.departName = departName;
    }
    public int getDepartSn() {
        return this.departSn;
    }
    
    public void setDepartSn(int departSn) {
        this.departSn = departSn;
    }




}


