package cn.edu.henu.rjxy.lms.model;
// Generated 2015-10-23 19:30:46 by Hibernate Tools 4.3.1



/**
 * Position generated by hbm2java
 */
public class Position  implements java.io.Serializable {


     private Integer positionId;
     private String positionName;
     private int positionSn;

    public Position() {
    }

    public Position(String positionName, int positionSn) {
       this.positionName = positionName;
       this.positionSn = positionSn;
    }
   
    public Integer getPositionId() {
        return this.positionId;
    }
    
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }
    public String getPositionName() {
        return this.positionName;
    }
    
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }
    public int getPositionSn() {
        return this.positionSn;
    }
    
    public void setPositionSn(int positionSn) {
        this.positionSn = positionSn;
    }




}


