package cn.edu.henu.rjxy.lms.model;
// Generated 2015-10-23 19:30:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {
     private Integer teacherId;
     private String teacherSn;//工号
     private String teacherName;//姓名
     private String teacherIdcard;//身份证 
     private int teacherCollegeId;//yuan

     private String teacherTel;//手机号 
     private String teacherQq;//qq 
     private String teacherPwd;//密码 
     private boolean teacherSex;//性别 
     private int teacherPositionId;//职称 
     private Date teacherEnrolling;//注册时间
     private int teacherRoleValue;

    public Teacher() {
    }

    public Teacher(String teacherSn, String teacherName, String teacherIdcard, int teacherCollegeId, String teacherTel, String teacherQq, String teacherPwd, boolean teacherSex, int teacherPositionId, Date teacherEnrolling, int teacherRoleValue) {
       this.teacherSn = teacherSn;
       this.teacherName = teacherName;
       this.teacherIdcard = teacherIdcard;
       this.teacherCollegeId = teacherCollegeId;
       this.teacherTel = teacherTel;
       this.teacherQq = teacherQq;
       this.teacherPwd = teacherPwd;
       this.teacherSex = teacherSex;
       this.teacherPositionId = teacherPositionId;
       this.teacherEnrolling = teacherEnrolling;
       this.teacherRoleValue = teacherRoleValue;
    }
    
    public void copy(TempTeacher tempTeacher){
            this.setTeacherId(tempTeacher.getTeacherId());
            this.setTeacherSn(tempTeacher.getTeacherSn());
            this.setTeacherName(tempTeacher.getTeacherName());
            this.setTeacherIdcard(tempTeacher.getTeacherIdcard());
            this.setTeacherCollegeId(tempTeacher.getTeacherCollegeId());
            this.setTeacherTel(tempTeacher.getTeacherTel());
            this.setTeacherQq(tempTeacher.getTeacherQq());
            this.setTeacherPwd(tempTeacher.getTeacherPwd());
            this.setTeacherSex(tempTeacher.getTeacherSex());
            this.setTeacherPositionId(tempTeacher.getTeacherPositionId());
            this.setTeacherEnrolling(tempTeacher.getTeacherEnrolling());
            this.setTeacherRoleValue(0);
    }
   
    public int getTeacherRoleValue() {
        return this.teacherRoleValue;
    }
    
    public void setTeacherRoleValue(int teacherRoleValue) {
        this.teacherRoleValue = teacherRoleValue;
    }

    /**
     * @return the teacherId
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * @param teacherId the teacherId to set
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * @return the teacherSn
     */
    public String getTeacherSn() {
        return teacherSn;
    }

    /**
     * @param teacherSn the teacherSn to set
     */
    public void setTeacherSn(String teacherSn) {
        this.teacherSn = teacherSn;
    }

    /**
     * @return the teacherName
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * @param teacherName the teacherName to set
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    /**
     * @return the teacherIdcard
     */
    public String getTeacherIdcard() {
        return teacherIdcard;
    }

    /**
     * @param teacherIdcard the teacherIdcard to set
     */
    public void setTeacherIdcard(String teacherIdcard) {
        this.teacherIdcard = teacherIdcard;
    }

    /**
     * @return the teacherCollegeId
     */
    public int getTeacherCollegeId() {
        return teacherCollegeId;
    }

    /**
     * @param teacherCollegeId the teacherCollegeId to set
     */
    public void setTeacherCollegeId(int teacherCollegeId) {
        this.teacherCollegeId = teacherCollegeId;
    }

    /**
     * @return the teacherTel
     */
    public String getTeacherTel() {
        return teacherTel;
    }

    /**
     * @param teacherTel the teacherTel to set
     */
    public void setTeacherTel(String teacherTel) {
        this.teacherTel = teacherTel;
    }

    /**
     * @return the teacherQq
     */
    public String getTeacherQq() {
        return teacherQq;
    }

    /**
     * @param teacherQq the teacherQq to set
     */
    public void setTeacherQq(String teacherQq) {
        this.teacherQq = teacherQq;
    }

    /**
     * @return the teacherPwd
     */
    public String getTeacherPwd() {
        return teacherPwd;
    }

    /**
     * @param teacherPwd the teacherPwd to set
     */
    public void setTeacherPwd(String teacherPwd) {
        this.teacherPwd = teacherPwd;
    }

    /**
     * @return the teacherSex
     */
    public boolean isTeacherSex() {
        return teacherSex;
    }

    /**
     * @param teacherSex the teacherSex to set
     */
    public void setTeacherSex(boolean teacherSex) {
        this.teacherSex = teacherSex;
    }

    /**
     * @return the teacherPositionId
     */
    public int getTeacherPositionId() {
        return teacherPositionId;
    }

    /**
     * @param teacherPositionId the teacherPositionId to set
     */
    public void setTeacherPositionId(int teacherPositionId) {
        this.teacherPositionId = teacherPositionId;
    }

    /**
     * @return the teacherEnrolling
     */
    public Date getTeacherEnrolling() {
        return teacherEnrolling;
    }

    /**
     * @param teacherEnrolling the teacherEnrolling to set
     */
    public void setTeacherEnrolling(Date teacherEnrolling) {
        this.teacherEnrolling = teacherEnrolling;
    }




}


