package cn.edu.henu.rjxy.lms.model;
// Generated 2015-10-23 19:30:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TempTeacher generated by hbm2java
 */
public class TempTeacherWithoutPwd  implements java.io.Serializable {



     private String teacherSn;//工号
     private String teacherName;//姓名
     private String teacherIdcard;//身份证 
     private String teacherCollege;//
     private String teacherTel;//手机号 
     private String teacherQq;//qq 
     private boolean teacherSex;//性别 
     private String teacherPosition;//职称 


    public TempTeacherWithoutPwd() {
    }

    public TempTeacherWithoutPwd(String teacherSn, String teacherName, String teacherIdcard, String teacherCollege, String teacherTel, String teacherQq, boolean teacherSex, String teacherPosition, Date teacherEnrolling) {
       this.teacherSn = teacherSn;
       this.teacherName = teacherName;
       this.teacherIdcard = teacherIdcard;
       this.teacherCollege = teacherCollege;
       this.teacherTel = teacherTel;
       this.teacherQq = teacherQq;
       this.teacherSex = teacherSex;
       this.teacherPosition = teacherPosition;

    }
    public void copy(TempTeacher tempTeacher){
       this.teacherSn = tempTeacher.getTeacherSn();
       this.teacherName = tempTeacher.getTeacherName();
       this.teacherIdcard = tempTeacher.getTeacherIdcard();
       this.teacherCollege = tempTeacher.getTeacherCollege();
       this.teacherTel = tempTeacher.getTeacherTel();
       this.teacherQq = tempTeacher.getTeacherQq();
       this.teacherSex = tempTeacher.getTeacherSex();
       this.teacherPosition = tempTeacher.getTeacherPosition();
    }
    public void copy(Teacher Teacher){
       this.teacherSn = Teacher.getTeacherSn();
       this.teacherName = Teacher.getTeacherName();
       this.teacherIdcard = Teacher.getTeacherIdcard();
       this.teacherCollege = Teacher.getTeacherCollege();
       this.teacherTel = Teacher.getTeacherTel();
       this.teacherQq = Teacher.getTeacherQq();
       this.teacherSex = Teacher.getTeacherSex();
       this.teacherPosition = Teacher.getTeacherPosition();
    }
    
   

    public String getTeacherSn() {
        return this.teacherSn;
    }
    
    public void setTeacherSn(String teacherSn) {
        this.teacherSn = teacherSn;
    }
    public String getTeacherName() {
        return this.teacherName;
    }
    
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }
    public String getTeacherIdcard() {
        return this.teacherIdcard;
    }
    
    public void setTeacherIdcard(String teacherIdcard) {
        this.teacherIdcard = teacherIdcard;
    }
    public String getTeacherCollege() {
        return this.teacherCollege;
    }
    
    public void setTeacherCollege(String teacherCollege) {
        this.teacherCollege = teacherCollege;
    }

    public String getTeacherTel() {
        return this.teacherTel;
    }
    
    public void setTeacherTel(String teacherTel) {
        this.teacherTel = teacherTel;
    }
    public String getTeacherQq() {
        return this.teacherQq;
    }
    
    public void setTeacherQq(String teacherQq) {
        this.teacherQq = teacherQq;
    }

    public boolean isTeacherSex() {
        return this.teacherSex;
    }
    
    public void setTeacherSex(boolean teacherSex) {
        this.teacherSex = teacherSex;
    }
    public String getTeacherPosition() {
        return this.teacherPosition;
    }
    
    public void setTeacherPositionId(String teacherPosition) {
        this.teacherPosition = teacherPosition;
    }

    public boolean getTeacherSex() {
        return this.teacherSex;
    }

}


