package cn.edu.henu.rjxy.lms.model;
// Generated 2015-10-23 19:30:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TempTeacher generated by hbm2java
 */
public class TempTeacher  implements java.io.Serializable {


     private Integer teacherId;
     private int teacherSn;//工号
     private String teacherName;//姓名
     private String teacherIdcard;//身份证 
     private int teacherCollegeId;//年级 
     private int teacherDepartId;// 系
     private String teacherTel;//手机号 
     private String teacherQq;//qq 
     private String teacherPwd;//密码 
     private boolean teacherSex;//性别 
     private int teacherPositionId;//职称 
     private Date teacherEnrolling;//注册时间

    public TempTeacher() {
    }

    public TempTeacher(int teacherSn, String teacherName, String teacherIdcard, int teacherCollegeId, int teacherDepartId, String teacherTel, String teacherQq, String teacherPwd, boolean teacherSex, int teacherPositionId, Date teacherEnrolling) {
       this.teacherSn = teacherSn;
       this.teacherName = teacherName;
       this.teacherIdcard = teacherIdcard;
       this.teacherCollegeId = teacherCollegeId;
       this.teacherDepartId = teacherDepartId;
       this.teacherTel = teacherTel;
       this.teacherQq = teacherQq;
       this.teacherPwd = teacherPwd;
       this.teacherSex = teacherSex;
       this.teacherPositionId = teacherPositionId;
       this.teacherEnrolling = teacherEnrolling;
    }
   
    public Integer getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
    public int getTeacherSn() {
        return this.teacherSn;
    }
    
    public void setTeacherSn(int teacherSn) {
        this.teacherSn = teacherSn;
    }
    public String getTeacherName() {
        return this.teacherName;
    }
    
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }
    public String getTeacherIdcard() {
        return this.teacherIdcard;
    }
    
    public void setTeacherIdcard(String teacherIdcard) {
        this.teacherIdcard = teacherIdcard;
    }
    public int getTeacherCollegeId() {
        return this.teacherCollegeId;
    }
    
    public void setTeacherCollegeId(int teacherCollegeId) {
        this.teacherCollegeId = teacherCollegeId;
    }
    public int getTeacherDepartId() {
        return this.teacherDepartId;
    }
    
    public void setTeacherDepartId(int teacherDepartId) {
        this.teacherDepartId = teacherDepartId;
    }
    public String getTeacherTel() {
        return this.teacherTel;
    }
    
    public void setTeacherTel(String teacherTel) {
        this.teacherTel = teacherTel;
    }
    public String getTeacherQq() {
        return this.teacherQq;
    }
    
    public void setTeacherQq(String teacherQq) {
        this.teacherQq = teacherQq;
    }
    public String getTeacherPwd() {
        return this.teacherPwd;
    }
    
    public void setTeacherPwd(String teacherPwd) {
        this.teacherPwd = teacherPwd;
    }
    public boolean isTeacherSex() {
        return this.teacherSex;
    }
    
    public void setTeacherSex(boolean teacherSex) {
        this.teacherSex = teacherSex;
    }
    public int getTeacherPositionId() {
        return this.teacherPositionId;
    }
    
    public void setTeacherPositionId(int teacherPositionId) {
        this.teacherPositionId = teacherPositionId;
    }
    public Date getTeacherEnrolling() {
        return this.teacherEnrolling;
    }
    
    public void setTeacherEnrolling(Date teacherEnrolling) {
        this.teacherEnrolling = teacherEnrolling;
    }




}


