package cn.edu.henu.rjxy.lms.model;
// Generated 2015-10-23 19:30:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TempStudent generated by hbm2java
 */
public class TempStudent  implements java.io.Serializable {


     private Integer studentId;
     private String studentSn;//学号
     private String studentName;//姓名
     private String studentIdcard;// 身份证 
     private int studentGrade; // 年级
     private int studentCollegeId;//院系
     private String studentTel;//手机号
     private String studentQq;//qq
     private String studentPwd;//密码 
     private boolean studentSex;//性别
     private Date studentEnrolling;//注册时间

    public TempStudent() {
    }

    public TempStudent(String studentSn, String studentName, String studentIdcard, int studentGrade, int studentCollegeId, String studentTel, String studentQq, String studentPwd, boolean studentSex, Date studentEnrolling) {
       this.studentSn = studentSn;
       this.studentName = studentName;
       this.studentIdcard = studentIdcard;
       this.studentGrade = studentGrade;
       this.studentCollegeId = studentCollegeId;
       this.studentTel = studentTel;
       this.studentQq = studentQq;
       this.studentPwd = studentPwd;
       this.studentSex = studentSex;
       this.studentEnrolling = studentEnrolling;
    }
   

    public String getStudentSn() {
        return this.studentSn;
    }
    
    public void setStudentSn(String studentSn) {
        this.studentSn = studentSn;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public String getStudentIdcard() {
        return this.studentIdcard;
    }
    
    public void setStudentIdcard(String studentIdcard) {
        this.studentIdcard = studentIdcard;
    }
    public int getStudentGrade() {
        return this.studentGrade;
    }
    
    public void setStudentGrade(int studentGrade) {
        this.studentGrade = studentGrade;
    }
    public int getStudentCollegeId() {
        return this.studentCollegeId;
    }
    
    public void setStudentCollegeId(int studentCollegeId) {
        this.studentCollegeId = studentCollegeId;
    }
    public String getStudentTel() {
        return this.studentTel;
    }
    
    public void setStudentTel(String studentTel) {
        this.studentTel = studentTel;
    }
    public String getStudentQq() {
        return this.studentQq;
    }
    
    public void setStudentQq(String studentQq) {
        this.studentQq = studentQq;
    }
    public String getStudentPwd() {
        return this.studentPwd;
    }
    
    public void setStudentPwd(String studentPwd) {
        this.studentPwd = studentPwd;
    }
    public boolean isStudentSex() {
        return this.studentSex;
    }
    
    public void setStudentSex(boolean studentSex) {
        this.studentSex = studentSex;
    }
    public boolean getStudentSex() {
        return this.studentSex;
    }
    
    public Date getStudentEnrolling() {
        return this.studentEnrolling;
    }
    
    public void setStudentEnrolling(Date studentEnrolling) {
        this.studentEnrolling = studentEnrolling;
    }

    /**
     * @return the studentId
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * @param studentId the studentId to set
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }




}


