package cn.edu.henu.rjxy.lms.model;
// Generated 2015-10-23 19:30:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TempStudent generated by hbm2java
 */
public class TempStudentWithoutPwd  implements java.io.Serializable {


     private Integer studentId;
     private String studentSn;//学号
     private String studentName;//姓名
     private String studentIdcard;// 身份证 
     private int studentGrade; // 年级
     private int studentCollegeId;//院系
     private String studentTel;//手机号
     private String studentQq;//qq
     private boolean studentSex;//性别
     private Date studentEnrolling;//注册时间

    public TempStudentWithoutPwd() {
    }

    public TempStudentWithoutPwd(String studentSn, String studentName, String studentIdcard, int studentGrade, int studentCollegeId, String studentTel, String studentQq, String studentPwd, boolean studentSex, Date studentEnrolling) {
       this.studentSn = studentSn;
       this.studentName = studentName;
       this.studentIdcard = studentIdcard;
       this.studentGrade = studentGrade;
       this.studentCollegeId = studentCollegeId;
       this.studentTel = studentTel;
       this.studentQq = studentQq;
       this.studentSex = studentSex;
       this.studentEnrolling = studentEnrolling;
    }
    public void copy(TempStudent tempStudent) {
       this.studentSn = tempStudent.getStudentSn();
       this.studentName = tempStudent.getStudentName();
       this.studentIdcard = tempStudent.getStudentIdcard();
       this.studentGrade = tempStudent.getStudentGrade();
       this.studentCollegeId = tempStudent.getStudentCollegeId();
       this.studentTel = tempStudent.getStudentTel();
       this.studentQq = tempStudent.getStudentQq();
       this.studentSex = tempStudent.getStudentSex();
       this.studentEnrolling = tempStudent.getStudentEnrolling();
    }
   
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
    public String getStudentSn() {
        return this.studentSn;
    }
    
    public void setStudentSn(String studentSn) {
        this.studentSn = studentSn;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public String getStudentIdcard() {
        return this.studentIdcard;
    }
    
    public void setStudentIdcard(String studentIdcard) {
        this.studentIdcard = studentIdcard;
    }
    public int getStudentGrade() {
        return this.studentGrade;
    }
    
    public void setStudentGrade(int studentGrade) {
        this.studentGrade = studentGrade;
    }
    public int getStudentCollegeId() {
        return this.studentCollegeId;
    }
    
    public void setStudentCollegeId(int studentCollegeId) {
        this.studentCollegeId = studentCollegeId;
    }
    public String getStudentTel() {
        return this.studentTel;
    }
    
    public void setStudentTel(String studentTel) {
        this.studentTel = studentTel;
    }
    public String getStudentQq() {
        return this.studentQq;
    }
    
    public void setStudentQq(String studentQq) {
        this.studentQq = studentQq;
    }

    public boolean isStudentSex() {
        return this.studentSex;
    }
    
    public void setStudentSex(boolean studentSex) {
        this.studentSex = studentSex;
    }
    public Date getStudentEnrolling() {
        return this.studentEnrolling;
    }
    
    public void setStudentEnrolling(Date studentEnrolling) {
        this.studentEnrolling = studentEnrolling;
    }




}


